### ISSUE TITLE
support .gitignore like file for ignore file show on session

### ISSUE THREAD

**Issue by bluelovers** [Genuitec/CodeTogether#179] opened 2020-08-10 23:13 UTC
**Is your feature request related to a problem? Please describe.**

support .gitignore like file for ignore file show on session

**Describe the solution you'd like**

> .codetogether/.ignore
```
.idea
some file list didn't wanna show for other people
```

**Describe your primary environment**
A clear and concise description of your environment, including host IDE, average number of participants, and roles.

**Describe alternatives you've considered**

**Additional context**

**Comment by brianvfernandes** [comment] 2020-08-11 10:36
We already support some of this in CodeTogether 2.1, and will be adding support for .gitingore like patterns too. Thank you for asking.

Duplicate of #178

**Closed by brianvfernandes** 2020-08-11 10:36 UTC
Labels: enhancement, unreviewed
