### ISSUE TITLE
Cannot trigger code assist when using a Spanish keyboard in a MacBook Pro

### ISSUE THREAD

**Issue by beleta** [Genuitec/CodeTogether#67] opened 2020-05-05 09:16 UTC
After pressing F1 I found that to trigger suggest I have to press `[^][space]`, but in a Spanish Mac keyboard I did not find the way do that.

CodeTogether correctly recognizes my keyboard as a Mac Spanish keyboard.

**Comment by brianvfernandes** [comment] 2020-05-05 10:55
`^` is the symbol for Control, so what you need to do is press `Control + Space`. Worked fine at our end, even when using a Spanish layout (though of course, that's not the same as a Spanish keyboard). Can you try that and let us know if it works?

**Comment by beleta** [comment] 2020-05-05 14:15
Yes, Control + Space , of course, is the first thing I tried. No, it does not work. I tried the integrated keyboard of my MacBook Pro , and an Apple USB external keyboard both with Spanish layouts.

**Comment by beleta** [comment] 2020-05-06 07:15
Works in Firefox and Safari, but not in Chrome or MS Edge.

**Comment by brianvfernandes** [comment] 2020-05-06 08:42
Thanks for the update - very odd. I have a few questions.

1. Just to be clear- what happens when you press Ctrl + Space on these browsers - I'm assuming nothing at all, correct?
2. What if you open the command palette and use the "Trigger Suggest" command - does that bring up the content assist? 
3. This shouldn't be a version problem because we disallow the use of unsupported browsers, but can you tell us the versions of both those browsers you are using? 
4. Also I'm assuming you're running these on the same macOS system? Any chance you could have a colleague join a session using those browsers from a different machine (whatever OS) and let us know if that works?

**Comment by beleta** [comment] 2020-05-06 15:58
1. Yes, this is correct.
2. Yes.
3. Chrome: 81.0.4044.138, Edge: 81.0.416.68
4. I tested myself what you proposed, results:
  - Windows on Parallels VM, does not work
  - Windows on physical machine thru MS Remote Desktop: DOES WORK!
  - Windows on physical machine thru Chrome Remote Desktop: does not work

**Comment by brianvfernandes** [comment] 2020-05-07 21:09
Given the nature of this issue, I doubt this will make a difference but what filetype are you editing, and what editor is that file open in, on the host side (I'm assuming host is Eclipse)?

The only idea we came up with is that Ctrl + Space is bound at the OS level to some other action, Chrome/Edge pass it on, while Firefox and Safari do not. Alternatively it could be bound at the browser level. is this something you could look into?

Just to be clear, we've specifically checked Chrome on MacOS, with Spanish keyboards, and it _does_ work just fine at our end.

**Comment by beleta** [comment] 2020-05-07 21:53
Ok, thank you Brian for trying it. I will try to find what's going on. I will keep you informed.

**Comment by wgalanciak** [comment] 2021-01-28 13:19
@beleta I am closing this issue as we cannot reproduce it. If you still observe the issue, we will reopen it.

**Closed by wgalanciak** 2021-01-28 13:19 UTC
Labels: browser, bug
