### ISSUE TITLE
[eclipse] cant' join to remote session inside eclipse

### ISSUE THREAD

**Issue by alef75** [Genuitec/CodeTogether#347] opened 2021-11-04 15:11 UTC
**Describe the bug**
From One instance of Eclipse ide CDT (2021-09) with codetogheter 5.0.0.202110 started an Host session

From another instance of Eclipse ide CDT (2021-09) with codetogheter 5.0.0.202110 join the previous remote session.
The session start to connect, the client advise for waiting authorization, in the server authorization is given, 
then in the client the session seem ok, but eclipse continue to show a progress bar "connecting" (see screen shot).
after a while eclipse give and error and the session on the client stops. see attachemnts for error log.

If we join the session from a browser all work right

**Screenshots**

**CodeTogether Host**
 - IDE: Eclipse
 - IDE 2021-09
 - OS: Ubuntu 
 - OS Version: 20.04

**IDE Participant**
- IDE: Eclipse
 - IDE 2021-09
 - OS: Ubuntu 
 - OS Version: 20.04

[eclipse.codetogheter.error.log](https://github.com/Genuitec/CodeTogether/files/7475780/eclipse.codetogheter.error.log)

![eclipse_codetogheter_error](https://user-images.githubusercontent.com/37915977/140341654-f606966b-057c-4235-a2aa-4e208640b37a.png)

**Comment by wgalanciak** [comment] 2021-11-04 17:11
@alef75, thanks for reporting the issue. We suspect that it may be related to the already known issue with large projects.
It is hard to define what a large project is, but maybe you could check, e.g. how many files are in it? Another test would be to start a session using the same environment but with a small project (e.g. newly created one).

**Comment by alef75** [comment] 2021-11-05 23:12
Hi @wgalanciak 
yes you are right, I'm using a very large project, it contains about 150000 files

**Comment by TimWebb** [comment] 2021-11-08 15:55
As a workaround, are some of those files built artifacts that you don't need?  If you use the right-click action to add to CodeTogether Ignore built artifacts, or manually add patterns of files not needed remotely, you may be able to get back up and running.  We are separately investigating changing a bit of how we deal with large workspaces and will likely have that available in a not-to-distant future.

**Comment by TimWebb** [comment] 2021-11-08 17:22
Closing as duplicate of issue #206

**Closed by TimWebb** 2021-11-08 17:22 UTC
Labels: bug, eclipse
