### ISSUE TITLE
Syntax highlighting for Scala

### ISSUE THREAD

**Issue by froth** [Genuitec/CodeTogether#137] opened 2020-06-29 07:18 UTC
**Is your feature request related to a problem? Please describe.**
There is no syntax highlighting for scala.

**Describe the solution you'd like**
Provide syntax highlighting for scala :)

**Describe your primary environment**
Intellij IDEA

**Comment by brianvfernandes** [comment] 2020-06-29 11:10
Duplicate of #112 
You'll be happy to know this has already been implemented and is coming in version 2.0. Thank you for asking!

**Closed by brianvfernandes** 2020-06-29 11:10 UTC
Labels: enhancement, unreviewed

**Comment by froth** [comment] 2020-06-29 11:26
Ah, I did not search closed issues, very nice!
