### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by IARI** [Genuitec/CodeTogether#273] opened 2021-03-05 07:04 UTC
I would like to use CodeTogether for little coding-challenges in Job interviews for a new dev position.
Striving for a quick and uncomplicated setup and equal conditions for everyone, I have only looked at the web-based editor.

So far it appears that autocompletion does not work.
For me (and applicants have confirmed this) the presence of autocompletion makes the main difference of an environment being usable or not. So since this is a big impediment for the applicants, right now I am offering the applicants to "play" the autocompletor by reading the options back to them aloud.

**Describe the solution you'd like**
I would like to have 
* Autocompletion options from the Host-IDE available to the guests in the web-based editor
* when selected by the guest, autocompletion actions should behave the same as if they had been selected in the host IDE

**Describe your primary environment**
Host IDE: jetbrains Rider
Participants: usually just 2: applicant and lead-dev guiding the challenge (me). Having other observers is a thought.

A little strawman for my case:
I could imagine that a design goal for you would be, to have the behavior of the web-ide somewhat independent from the choice of host-IDE, so having different auto-completion options would violate this. However i believe that the benefit of autocompletion should be considered.

**In case that this is an existing feature that should work already**
I'm not sure about this - the readme says 'Host-provided language smarts' and mentions content assist - should this already include what i am asking for?
In that case consider this a bug report or support request, since it appears to not be working for me.

**Comment by brianvfernandes** [comment] 2021-03-05 10:18
@IARI thank you for the detailed report - we're happy to see CodeTogether being used by more people in an interview setting.

The good news is that auto complete does work in the browser for most languages, no matter what IDE you host with (we show this in action in several of our videos, documentation and even on our home page). The bad news, is that Rider's unique architecture prevents us from making most of these language capabilities available to participants, and it requires a special implementation of the CodeTogether plugin. This is documented in issue #79  - when Rider _specifically_ is used as a host, those language features are absent. 

The only workaround I can suggest for now is to use another IDE for the interviews, but I realize this is easier said than done. I'm marking this a duplicate of #79, do consider leaving a comment and/or voting on that issue.

**Closed by brianvfernandes** 2021-03-05 10:18 UTC
Labels: enhancement, unreviewed
